# url: http://detro.github.io
# url: http://localhost:4000
url: http://ivandemarino.me

name: "Too much coffee, too little time"
author: "Ivan De Marino"
authors:
    detro: "Ivan De Marino"

title: "Too much <strong>coffee</strong><br/>too little <strong>time</strong>"
subtitle: "Ivan<strong>DeMarino</strong>"

internal-links:
    - title: blog
      link: /
    - title: projects
      link: /projects
    - title: about me
      link: /about-me
    - title: archive
      link: /archive

rel-me-links:
    - icon: twitter
      link: https://twitter.com/detronizator
    - icon: github
      link: https://github.com/detro
    - icon: linkedin
      link: http://linkedin.com/in/ivandemarino
    - icon: instagram
      link: http://instagram.com/detronizator
    - icon: rss
      link: http://detro.github.io/rss.xml

meta:
    host:
        name: GitHub Pages
        link: http://pages.github.com/
    engine:
        name: Jekyll
        link: http://jekyllrb.com/
    theme-author:
        name: Ivan De Marino
        link: http://ivandemarino.me
    license:
        name: CC ASA 3.0
        link: http://creativecommons.org/licenses/by-sa/3.0/

destination: ../detro.github.io-destination

markdown: redcarpet
pygments: true
lessc: /usr/local/share/npm/bin/lessc

permalink: /:year/:month/:title

paginate: 10
paginate_path: 'blog/:num'

google_analytics:
    account: UA-136869-11

# limit_posts: 50
