name: "Too much Coffee,<br/>too little Time"
author: "Ivan De Marino"

internal-links:
    - title: blog
      link: /
    - title: projects
      link: /projects
    - title: about me
      link: /about-me
    - title: archive
      link: /archive

rel-me-links:
    - icon: twitter
      link: https://twitter.com/detronizator
    - icon: github
      link: https://github.com/detro
    - icon: linkedin
      link: http://linkedin.com/in/ivandemarino
    - icon: instagram
      link: http://instagram.com/detronizator
    - icon: rss
      link: rss

meta:
    host:
        name: GitHub Pages
        link: http://pages.github.com/
    engine:
        name: Jekyll
        link: http://jekyllrb.com/
    theme-author:
        name: Ivan De Marino
        link: http://ivandemarino.me
    license:
        name: CC ASA 3.0
        link: http://creativecommons.org/licenses/by-sa/3.0/

destination: ../detro.github.io-destination

markdown: redcarpet
pygments: true
lessc: /usr/local/share/npm/bin/lessc

permalink: /:year/:month/:title

paginate: 9
paginate_path: 'blog/:num'

limit_posts: 50
