name: "Too much Coffee, too little Time"
author: "Ivan De Marino"

destination: ../detro.github.io-destination

markdown: redcarpet
pygments: true

permalink: /:year/:month/:title

paginate: 10
paginate_path: 'blog/:num'

excerpt_separator: "\n"

limit_posts: 20
