# url: http://detro.github.io
# url: http://localhost:4000
url: http://ivandemarino.me

# Basics
name: "Too much coffee, too little time"
description: "Ivan De Marino's blog and personal website"
title: "Too much coffee, too little time"
title-display: "Too much <strong>coffee</strong><br/>too little <strong>time</strong>"
subtitle-display: "Ivan <strong>De Marino</strong>"
author: "Ivan De Marino"
authors:
  detro: "Ivan De Marino"

# Links
## Internal links
internal-links:
  - title: blog
    link: /
  - title: projects
    link: /projects
  - title: about me
    link: /about-me
  - title: archive
    link: /archive
## Related-to-me links
rel-me-links:
  - icon: twitter
    link: https://twitter.com/detronizator
  - icon: github
    link: https://github.com/detro
  - icon: linkedin
    link: http://linkedin.com/in/ivandemarino
  - icon: rss
    link: http://ivandemarino.me/atom.xml
  - icon: sitemap
    link: http://ivandemarino.me/sitemap.xml
## Other links
meta:
  host:
    name: GitHub Pages
    link: http://pages.github.com/
  engine:
    name: Jekyll
    link: http://jekyllrb.com/
  theme-author:
    name: Ivan De Marino
    link: http://ivandemarino.me
  license:
    name: CC BY 4.0
    link: https://creativecommons.org/licenses/by/4.0/

destination: ../gh-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .nvmrc
  - .ruby-version
  - Makefile

# HTML/CSS generation options
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
lessc: lessc
encoding: utf-8

permalink: /:year/:month/:title
paginate: 10
paginate_path: 'blog/:num'

# GitHub Pages gems
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Jekyll feed plugin
feed:
  path: atom.xml

# Jekyll mentions plugin
jekyll-mentions:
  base_url: https://twitter.com

# Google Analytics 4 Configuration
google_analytics_4:
  config: G-K0JQTBH0J9

# limit_posts: 50 #< Useful when developing
