name: "Too much Coffee, too little Time"
author: "Ivan De Marino"

rel-me:
    - icon: twitter
      link: https://twitter.com/detronizator
    - icon: github
      link: https://github.com/detro
    - icon: linkedin
      link: http://linkedin.com/in/ivandemarino
    - icon: google-plus
      link: https://plus.google.com/117520225301299920042/posts
    - icon: instagram
      link: http://instagram.com/detronizator
    - icon: rss
      link: rss

destination: ../detro.github.io-destination

markdown: redcarpet
pygments: true

permalink: /:year/:month/:title

paginate: 10
paginate_path: 'blog/:num'

limit_posts: 40
